# fly.toml app configuration file generated for solobase-lingering-bird-7226 on 2025-09-09T19:42:58+12:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#
# To deploy can run fly deploy --config solobase/fly-demo.toml --dockerfile solobase/Dockerfile.fly in parent folder

app = 'solobase-demo'
primary_region = 'syd'

[build]
  dockerfile = "Dockerfile.fly"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '256MB'
  cpu_kind = 'shared'
  cpus = 1
