/**
 * solobase-web/worker — Composable exports for integrating Solobase into an
 * existing Service Worker.
 *
 * Usage (inside your own service-worker.js):
 *
 *   import { initialize, handleRequest } from 'solobase-web/worker';
 *
 *   await initialize();
 *
 *   self.addEventListener('fetch', (event) => {
 *     const url = new URL(event.request.url);
 *     if (url.pathname.startsWith('/b/') || url.pathname === '/health') {
 *       event.respondWith(handleRequest(event.request));
 *       return;
 *     }
 *     // ... your existing SW logic
 *   });
 */

// Re-export the raw wasm-bindgen entry points.
// At build time, the WASM binary and glue JS are copied into dist/ alongside
// this file. The imports resolve to the wasm-bindgen-generated module.

// @ts-expect-error — generated by wasm-pack, no TS declarations at source level
import wasmInit, {
  initialize as wasmInitialize,
  handle_request as wasmHandleRequest,
} from '../../pkg/solobase_web.js';

let initialized = false;
let initPromise: Promise<void> | null = null;

/**
 * Load the WASM module and boot the Solobase runtime.
 * Safe to call multiple times — only the first call does work.
 */
export async function initialize(): Promise<void> {
  if (initialized) return;
  if (initPromise) return initPromise;

  initPromise = (async () => {
    await wasmInit();
    await wasmInitialize();
    initialized = true;
  })();

  return initPromise;
}

/**
 * Route a fetch Request through the Solobase WASM runtime.
 * Returns a Response. Callers must ensure `initialize()` has completed first.
 */
export async function handleRequest(request: Request): Promise<Response> {
  if (!initialized) {
    await initialize();
  }
  return wasmHandleRequest(request);
}
