import { test, expect } from '@playwright/test';
import { loginAsAdmin } from './fixtures/auth';

const ANON_ROUTES = [
  { path: '/b/auth/login', name: 'auth-login' },
  { path: '/b/auth/signup', name: 'auth-signup' },
  { path: '/totally-not-a-thing', name: 'status-404' },
];

const ADMIN_ROUTES = [
  { path: '/', name: 'root-redirect' },
  { path: '/b/admin/', name: 'admin-dashboard' },
  { path: '/b/admin/users', name: 'admin-users' },
  { path: '/b/admin/blocks', name: 'admin-blocks' },
  { path: '/b/admin/database', name: 'admin-database' },
  // admin-storage dropped — the storage-access-error table accumulates rows
  // generated by the baseline run itself, so the snapshot drifts between local
  // and CI runs depending on test-traffic volume. Same drift category Phase 4
  // PR-3 dropped admin-dashboard-mobile for.
  { path: '/b/admin/logs', name: 'admin-logs' },
  { path: '/b/admin/email', name: 'admin-email' },
  { path: '/b/admin/network', name: 'admin-network' },
  { path: '/b/admin/variables', name: 'admin-variables' },
  { path: '/b/admin/permissions', name: 'admin-permissions' },
  { path: '/b/auth/dashboard', name: 'portal-dashboard' },
  { path: '/b/auth/orgs', name: 'portal-orgs' },
  { path: '/b/userportal/profile', name: 'portal-profile' },
  { path: '/b/userportal/sessions', name: 'portal-sessions' },
  { path: '/b/userportal/security', name: 'portal-security' },
  { path: '/b/products/', name: 'portal-products' },
  { path: '/b/llm/', name: 'llm-chat' },
];

const COMMON_OPTS = {
  fullPage: true as const,
  maxDiffPixelRatio: 0.01,
  // Mask elements that vary per render (timestamps, counts, generated IDs).
  // Tests can override per-route if needed.
};

test.describe('visual baseline — anonymous', () => {
  for (const r of ANON_ROUTES) {
    test(`anon ${r.name}`, async ({ page }) => {
      await page.goto(r.path, { waitUntil: 'networkidle' });
      await expect(page).toHaveScreenshot(`anon-${r.name}.png`, COMMON_OPTS);
    });
  }
});

test.describe('visual baseline — admin', () => {
  test.beforeEach(async ({ page }) => {
    await loginAsAdmin(page);
  });
  for (const r of ADMIN_ROUTES) {
    test(`admin ${r.name}`, async ({ page }) => {
      await page.goto(r.path, { waitUntil: 'networkidle' });
      await expect(page).toHaveScreenshot(`admin-${r.name}.png`, {
        ...COMMON_OPTS,
        // Mask relative timestamps anywhere they appear.
        mask: [page.locator('[data-relative-time], .relative-time, time')],
      });
    });
  }
});

// ===== Phase 4 PR-3: 375px mobile pass =====

const MOBILE_VIEWPORT = { width: 375, height: 812 } as const;

const MOBILE_ANON_ROUTES = [
  { path: '/b/auth/login', name: 'auth-login' },
  { path: '/b/auth/signup', name: 'auth-signup' },
];

const MOBILE_ADMIN_ROUTES = [
  // Portal pages — primary mobile audience. Admin is desktop-first per
  // master spec; the hint banner inside is the explicit accommodation.
  // Admin pages aren't mobile-snapshotted because the dashboard's
  // "Recent Errors" table is fed by the request_log accumulated during
  // the rest of the baseline run, so its content + width drift between
  // local and CI.
  { path: '/b/auth/dashboard', name: 'portal-dashboard' },
  { path: '/b/auth/orgs', name: 'portal-orgs' },
  { path: '/b/userportal/profile', name: 'portal-profile' },
  { path: '/b/userportal/sessions', name: 'portal-sessions' },
  { path: '/b/userportal/security', name: 'portal-security' },
  { path: '/b/products/', name: 'portal-products' },
  { path: '/b/llm/', name: 'llm-chat' },
];

// ===== Phase 5b PR-1: vector index admin pages =====

const VECTOR_INDEX = 'docs';
const VECTOR_DIMS = 384;

test.describe('visual baseline — admin vector', () => {
  test.beforeEach(async ({ page }) => {
    await loginAsAdmin(page);
  });

  test('admin-vector-list-desktop', async ({ page }) => {
    // Seed one index so the listing has a row (otherwise we'd snapshot the
    // empty state, which is covered by unit tests).
    const create = await page.request.post('/b/vector/api/indexes', {
      data: {
        name: VECTOR_INDEX,
        model: 'multilingual-e5-small',
        dimensions: VECTOR_DIMS,
        metric: 'cosine',
        keyword_search: true,
      },
    });
    expect(create.status()).toBe(200);

    // Upsert one vector so the count cell is non-zero (deterministic).
    const v = Array.from({ length: VECTOR_DIMS }, (_, i) => (i === 0 ? 1 : 0));
    const upsert = await page.request.post('/b/vector/api/upsert', {
      data: {
        index: VECTOR_INDEX,
        entries: [{ id: 'doc-A', vector: v }],
      },
    });
    expect(upsert.status()).toBe(200);

    try {
      await page.goto('/b/vector/', { waitUntil: 'networkidle' });
      await expect(page).toHaveScreenshot('admin-vector-list-desktop.png', {
        ...COMMON_OPTS,
        mask: [page.locator('[data-relative-time], .relative-time, time')],
      });
    } finally {
      await page.request.delete(`/b/vector/api/indexes/${VECTOR_INDEX}`);
    }
  });

  test('admin-vector-detail-desktop', async ({ page }) => {
    const create = await page.request.post('/b/vector/api/indexes', {
      data: {
        name: VECTOR_INDEX,
        model: 'multilingual-e5-small',
        dimensions: VECTOR_DIMS,
        metric: 'cosine',
        keyword_search: true,
      },
    });
    expect(create.status()).toBe(200);

    const v = Array.from({ length: VECTOR_DIMS }, (_, i) => (i === 0 ? 1 : 0));
    const upsert = await page.request.post('/b/vector/api/upsert', {
      data: {
        index: VECTOR_INDEX,
        entries: [{ id: 'doc-A', vector: v }],
      },
    });
    expect(upsert.status()).toBe(200);

    try {
      await page.goto(`/b/vector/${VECTOR_INDEX}/`, { waitUntil: 'networkidle' });
      await expect(page).toHaveScreenshot('admin-vector-detail-desktop.png', {
        ...COMMON_OPTS,
        mask: [page.locator('[data-relative-time], .relative-time, time')],
      });
    } finally {
      await page.request.delete(`/b/vector/api/indexes/${VECTOR_INDEX}`);
    }
  });
});

test.describe('visual baseline mobile — anonymous (375px)', () => {
  for (const r of MOBILE_ANON_ROUTES) {
    test(`anon-mobile ${r.name}`, async ({ page }) => {
      await page.setViewportSize(MOBILE_VIEWPORT);
      await page.goto(r.path, { waitUntil: 'networkidle' });
      await expect(page).toHaveScreenshot(`anon-${r.name}-mobile.png`, COMMON_OPTS);
    });
  }
});

test.describe('visual baseline mobile — admin (375px)', () => {
  test.beforeEach(async ({ page }) => {
    await page.setViewportSize(MOBILE_VIEWPORT);
    await loginAsAdmin(page);
  });
  for (const r of MOBILE_ADMIN_ROUTES) {
    test(`admin-mobile ${r.name}`, async ({ page }) => {
      await page.setViewportSize(MOBILE_VIEWPORT);
      await page.goto(r.path, { waitUntil: 'networkidle' });
      await expect(page).toHaveScreenshot(`admin-${r.name}-mobile.png`, {
        ...COMMON_OPTS,
        mask: [page.locator('[data-relative-time], .relative-time, time')],
      });
    });
  }
});
