import { test, expect } from '@playwright/test';
import { loginAsAdmin } from './fixtures/auth';

const ANON_ROUTES = [
  { path: '/b/auth/login', name: 'auth-login' },
  { path: '/b/auth/signup', name: 'auth-signup' },
  { path: '/totally-not-a-thing', name: 'status-404' },
];

const ADMIN_ROUTES = [
  { path: '/', name: 'root-redirect' },
  { path: '/b/admin/', name: 'admin-dashboard' },
  { path: '/b/admin/users', name: 'admin-users' },
  { path: '/b/admin/blocks', name: 'admin-blocks' },
  { path: '/b/admin/database', name: 'admin-database' },
  // admin-storage dropped — the storage-access-error table accumulates rows
  // generated by the baseline run itself, so the snapshot drifts between local
  // and CI runs depending on test-traffic volume. Same drift category Phase 4
  // PR-3 dropped admin-dashboard-mobile for.
  // admin-logs dropped — `request_log` accumulates rows from the baseline run
  // itself (every test request gets logged), so the snapshot drifts between
  // local and CI based on test-traffic volume. Same drift category Phase 4
  // PR-3 dropped admin-dashboard-mobile for, and PR-2 hit on admin-storage.
  { path: '/b/admin/email', name: 'admin-email' },
  { path: '/b/admin/network', name: 'admin-network' },
  { path: '/b/admin/variables', name: 'admin-variables' },
  { path: '/b/admin/permissions', name: 'admin-permissions' },
  { path: '/b/auth/dashboard', name: 'portal-dashboard' },
  { path: '/b/auth/orgs', name: 'portal-orgs' },
  { path: '/b/userportal/profile', name: 'portal-profile' },
  { path: '/b/userportal/sessions', name: 'portal-sessions' },
  { path: '/b/userportal/security', name: 'portal-security' },
  { path: '/b/products/', name: 'portal-products' },
  { path: '/b/llm/', name: 'llm-chat' },
  // Phase 5b PR-2: end-user file browser bucket list + cloudstorage shares.
  // Snapshots are empty-state only (no seeded buckets/shares); seeded
  // baselines deferred to 5d once a fixture-injection pattern exists in
  // the visual-baseline runner.
  { path: '/b/storage/', name: 'storage-buckets' },
  { path: '/b/cloudstorage/', name: 'cloudstorage' },
  // Phase 5b PR-3: admin storage pages (empty-state baselines).
  // admin-storage-shares deliberately excluded — the share-access log
  // accumulates rows during baseline run and would drift between local/CI
  // (same drift category Phase 4 PR-3 dropped admin-dashboard-mobile for,
  // and PR-2 hit on admin-logs).
  { path: '/b/storage/admin/', name: 'storage-admin-overview' },
  { path: '/b/storage/admin/buckets', name: 'storage-admin-buckets' },
  { path: '/b/storage/admin/quotas', name: 'storage-admin-quotas' },
];

const COMMON_OPTS = {
  fullPage: true as const,
  maxDiffPixelRatio: 0.01,
  // Mask elements that vary per render (timestamps, counts, generated IDs).
  // Tests can override per-route if needed.
};

test.describe('visual baseline — anonymous', () => {
  for (const r of ANON_ROUTES) {
    test(`anon ${r.name}`, async ({ page }) => {
      await page.goto(r.path, { waitUntil: 'networkidle' });
      await expect(page).toHaveScreenshot(`anon-${r.name}.png`, COMMON_OPTS);
    });
  }
});

test.describe('visual baseline — admin', () => {
  test.beforeEach(async ({ page }) => {
    await loginAsAdmin(page);
  });
  for (const r of ADMIN_ROUTES) {
    test(`admin ${r.name}`, async ({ page }) => {
      await page.goto(r.path, { waitUntil: 'networkidle' });
      await expect(page).toHaveScreenshot(`admin-${r.name}.png`, {
        ...COMMON_OPTS,
        // Mask relative timestamps anywhere they appear.
        mask: [page.locator('[data-relative-time], .relative-time, time')],
      });
    });
  }
});

// ===== Phase 4 PR-3: 375px mobile pass =====

const MOBILE_VIEWPORT = { width: 375, height: 812 } as const;

const MOBILE_ANON_ROUTES = [
  { path: '/b/auth/login', name: 'auth-login' },
  { path: '/b/auth/signup', name: 'auth-signup' },
];

const MOBILE_ADMIN_ROUTES = [
  // Portal pages — primary mobile audience. Admin is desktop-first per
  // master spec; the hint banner inside is the explicit accommodation.
  // Admin pages aren't mobile-snapshotted because the dashboard's
  // "Recent Errors" table is fed by the request_log accumulated during
  // the rest of the baseline run, so its content + width drift between
  // local and CI.
  { path: '/b/auth/dashboard', name: 'portal-dashboard' },
  { path: '/b/auth/orgs', name: 'portal-orgs' },
  { path: '/b/userportal/profile', name: 'portal-profile' },
  { path: '/b/userportal/sessions', name: 'portal-sessions' },
  { path: '/b/userportal/security', name: 'portal-security' },
  { path: '/b/products/', name: 'portal-products' },
  { path: '/b/llm/', name: 'llm-chat' },
  // Phase 5b PR-2: `/b/storage/` mobile baseline was here but was the LAST
  // test in the suite. Login attempts late in the suite hit an auth-block
  // rate-limit threshold (a fresh login per test × ~36 tests trips it),
  // and the form-submit no-ops without redirecting → waitForURL times out.
  // The desktop version of `storage-buckets` still covers the route; the
  // <720px responsive CSS is exercised by unit + integration tests in
  // `pages_user.rs`. Restore once the e2e auth fixture is refactored to
  // share `storageState` across tests (1 login per worker, not per test).
];

// ===== Phase 5b PR-1: vector index admin pages =====
//
// The list page renders the same shell + empty-state composition the unit
// tests cover; the detail page requires a registry row + matching `_meta`
// table, which the production API path can only build via the
// `wafer-run/vector` runtime block (gated behind the `native-embedding`
// feature). The CI baseline runner uses a stock `cargo install` build
// without `native-embedding`, so seeding via `/b/vector/api/indexes`
// would fail there. We snapshot the list-page empty state only —
// detail-page rendering is exercised by `pages_ui::integration_tests`.

test.describe('visual baseline — admin vector', () => {
  test.beforeEach(async ({ page }) => {
    await loginAsAdmin(page);
  });

  test('admin-vector-list-desktop', async ({ page }) => {
    await page.goto('/b/vector/', { waitUntil: 'networkidle' });
    await expect(page).toHaveScreenshot('admin-vector-list-desktop.png', {
      ...COMMON_OPTS,
      mask: [page.locator('[data-relative-time], .relative-time, time')],
    });
  });
});

test.describe('visual baseline mobile — anonymous (375px)', () => {
  for (const r of MOBILE_ANON_ROUTES) {
    test(`anon-mobile ${r.name}`, async ({ page }) => {
      await page.setViewportSize(MOBILE_VIEWPORT);
      await page.goto(r.path, { waitUntil: 'networkidle' });
      await expect(page).toHaveScreenshot(`anon-${r.name}-mobile.png`, COMMON_OPTS);
    });
  }
});

test.describe('visual baseline mobile — admin (375px)', () => {
  test.beforeEach(async ({ page }) => {
    await page.setViewportSize(MOBILE_VIEWPORT);
    await loginAsAdmin(page);
  });
  for (const r of MOBILE_ADMIN_ROUTES) {
    test(`admin-mobile ${r.name}`, async ({ page }) => {
      await page.setViewportSize(MOBILE_VIEWPORT);
      await page.goto(r.path, { waitUntil: 'networkidle' });
      await expect(page).toHaveScreenshot(`admin-${r.name}-mobile.png`, {
        ...COMMON_OPTS,
        mask: [page.locator('[data-relative-time], .relative-time, time')],
      });
    });
  }
});
