//! wrangler.toml generation + override merging.
//!
//! [`CloudflareConfig`] is the *resolved* shape consumed by [`generate`].
//! Parsing solobase.toml + applying env-var overlays lives in
//! [`super::env`], which produces this type.

use std::path::{Path, PathBuf};

use anyhow::{Context, Result};

#[derive(Debug, Clone)]
pub struct CloudflareConfig {
    pub account_id: String,
    pub worker_name: String,
    pub compatibility_date: String,
    pub d1: D1Config,
    pub r2: R2Config,
    /// Path (relative to consumer repo root) to a TOML file whose contents
    /// are deep-merged over the generated defaults. None means "no overrides."
    pub wrangler_overrides_path: Option<PathBuf>,
}

#[derive(Debug, Clone)]
pub struct D1Config {
    pub binding: String,
    pub database_name: String,
    pub database_id: String,
}

#[derive(Debug, Clone)]
pub struct R2Config {
    pub binding: String,
    pub bucket_name: String,
}

pub fn generate(cfg: &CloudflareConfig, repo_root: &Path, out_dir: &Path) -> Result<PathBuf> {
    let mut value = base_toml(cfg);

    if let Some(rel) = cfg.wrangler_overrides_path.as_ref() {
        let abs = repo_root.join(rel);
        let raw = std::fs::read_to_string(&abs)
            .with_context(|| format!("read overrides {}", abs.display()))?;
        let overrides: toml::Value =
            toml::from_str(&raw).with_context(|| format!("parse overrides {}", abs.display()))?;
        deep_merge(&mut value, overrides);
    }

    let body = toml::to_string_pretty(&value).context("serialize wrangler.toml")?;
    let header = "# Generated by `solobase build --target cloudflare`. \
                  Do not edit. Regenerated each build.\n\n";
    let path = out_dir.join("wrangler.toml");
    std::fs::write(&path, format!("{header}{body}"))
        .with_context(|| format!("write {}", path.display()))?;
    Ok(path)
}

fn base_toml(cfg: &CloudflareConfig) -> toml::Value {
    use toml::Value;

    let mut root = toml::map::Map::new();
    root.insert("name".into(), Value::String(cfg.worker_name.clone()));
    root.insert(
        "main".into(),
        Value::String("../../build/worker/shim.mjs".into()),
    );
    root.insert(
        "compatibility_date".into(),
        Value::String(cfg.compatibility_date.clone()),
    );

    let mut build = toml::map::Map::new();
    build.insert(
        "command".into(),
        Value::String(
            "cargo install worker-build --quiet && \
             worker-build --release --no-default-features \
             --features target-cloudflare"
                .into(),
        ),
    );
    root.insert("build".into(), Value::Table(build));

    let mut d1_entry = toml::map::Map::new();
    d1_entry.insert("binding".into(), Value::String(cfg.d1.binding.clone()));
    d1_entry.insert(
        "database_name".into(),
        Value::String(cfg.d1.database_name.clone()),
    );
    d1_entry.insert(
        "database_id".into(),
        Value::String(cfg.d1.database_id.clone()),
    );
    root.insert(
        "d1_databases".into(),
        Value::Array(vec![Value::Table(d1_entry)]),
    );

    let mut r2_entry = toml::map::Map::new();
    r2_entry.insert("binding".into(), Value::String(cfg.r2.binding.clone()));
    r2_entry.insert(
        "bucket_name".into(),
        Value::String(cfg.r2.bucket_name.clone()),
    );
    root.insert(
        "r2_buckets".into(),
        Value::Array(vec![Value::Table(r2_entry)]),
    );

    Value::Table(root)
}

/// Deep-merge `overrides` into `base`. Tables merge recursively;
/// arrays and primitives are replaced wholesale.
fn deep_merge(base: &mut toml::Value, overrides: toml::Value) {
    use toml::Value;
    match (base, overrides) {
        (Value::Table(b), Value::Table(o)) => {
            for (k, v) in o {
                match b.get_mut(&k) {
                    Some(existing) => deep_merge(existing, v),
                    None => {
                        b.insert(k, v);
                    }
                }
            }
        }
        (slot, replacement) => *slot = replacement,
    }
}
