#!/usr/bin/env bash
# Rebuild sql.js with FTS5 enabled and vendor the artifacts into solobase-browser.
#
# Why: the upstream sql.js npm package ships a build with FTS3/FTS4 only.
# Browser vector keyword/hybrid search (suppers-ai/vector) needs FTS5 syntax
# (MATCH ... ORDER BY rank, BM25). We rebuild from the same upstream tag the
# vendored 1.11.0 came from, with one extra Emscripten define.
#
# Inputs: none. Idempotent. Writes to:
#   - crates/solobase-browser/assets/vendor/sql-wasm.wasm
#   - crates/solobase-browser/assets/vendor/sql-wasm-esm.js

set -euo pipefail

SQL_JS_TAG="v1.11.0"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
WORK_DIR="$(mktemp -d)"
VENDOR_DIR="${SCRIPT_DIR}/../crates/solobase-browser/assets/vendor"

trap 'rm -rf "${WORK_DIR}"' EXIT

echo "[1/4] cloning sql.js ${SQL_JS_TAG} into ${WORK_DIR}"
git clone --depth 1 --branch "${SQL_JS_TAG}" https://github.com/sql-js/sql.js.git "${WORK_DIR}/sql.js"
cd "${WORK_DIR}/sql.js"

echo "[2/4] building with FTS5 (Docker, may take 5-10 min)"
make clean || true
EMFLAGS_FEATURES="-DSQLITE_ENABLE_FTS3 -DSQLITE_ENABLE_FTS3_PARENTHESIS -DSQLITE_ENABLE_FTS5" \
  make all

echo "[3/4] vendoring artifacts to ${VENDOR_DIR}"
mkdir -p "${VENDOR_DIR}"
cp dist/sql-wasm.wasm "${VENDOR_DIR}/sql-wasm.wasm"

# Regenerate the ESM wrapper around the new UMD JS. The upstream UMD output is
# `dist/sql-wasm.js`; we wrap it in the same IIFE shape the prior wrapper used.
{
  echo "// ESM wrapper for sql.js ${SQL_JS_TAG#v} UMD build with FTS5 (IIFE to isolate scope)"
  echo "// Generated by scripts/build-sql-js-fts5.sh — do not edit by hand."
  echo 'const _sqlJs = (function() {'
  echo '  var module = { exports: {} };'
  echo '  var exports = module.exports;'
  echo ''
  cat dist/sql-wasm.js
  echo ''
  echo '  return module.exports.default || module.exports;'
  echo '})();'
  echo 'export default _sqlJs;'
} > "${VENDOR_DIR}/sql-wasm-esm.js"

echo "[4/4] verifying FTS5 symbol present in new wasm"
if ! strings "${VENDOR_DIR}/sql-wasm.wasm" | grep -qi "fts5"; then
  echo "ERROR: FTS5 symbols missing from rebuilt wasm — build flag did not take effect" >&2
  exit 1
fi

echo "done. New artifacts:"
ls -la "${VENDOR_DIR}/sql-wasm.wasm" "${VENDOR_DIR}/sql-wasm-esm.js"
